"""describe your changes

Revision ID: c6a8d9188ebc
Revises: 
Create Date: 2025-05-16 22:25:06.533546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a8d9188ebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_name', sa.String(), nullable=True),
    sa.Column('updated_by_user_name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('test', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_users_user_email'), 'users', ['user_email'], unique=True, schema='master')
    op.create_index(op.f('ix_master_users_user_id'), 'users', ['user_id'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_users_user_id'), table_name='users', schema='master')
    op.drop_index(op.f('ix_master_users_user_email'), table_name='users', schema='master')
    op.drop_table('users', schema='master')
    # ### end Alembic commands ###
